services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    networks:
      - app-net
  database:
    image: postgres
    restart: always
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./.data/postgresql:/bitnami/postgresql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
